config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'static_pages/about'
  get 'static_pages/found'
  get 'static_pages/lost'
  get 'static_pages/login'
  get 'static_pages/signup'
  root 'static_pages#lost'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
require 'test_helper'
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "create success"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
  # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.erb
<div class="footer" id ="navbar" style="margin-top: 20px">
        <p>
          footer</p>
      </div>

app/views/layouts/_header.html.erb
<section class="about-header about-header-image"></section>
<div id="navbar">
    <%= link_to "Lost Items" , static_pages_lost_path %> 
    <%= link_to "Found Items" , static_pages_found_path %>
    <%= link_to "About" , static_pages_about_path %>
    <% if logged_in? %>
        <li><%= link_to "Username", current_user %></li>
        <li>
            <%= link_to "Sign out", static_pages_lost_path, method: :delete %>
        </li>
    <% else %>
          <li><%= link_to "Sign in", static_pages_login_path %></li>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title><%= yield(:title) %> | LostAndFound</title>
 <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
        <link href="testproject/app/assets/stylesheets/bootstrap-material-design.css" rel="stylesheet">
        <link href="testproject/app/assets/stylesheets/main.css" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Quantico" rel="stylesheet">
  </head>
  <body>
        <%= render "layouts/header" %>
        <%= yield %>
        <%= render "layouts/footer" %>
      
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="container">    
    <div class="section-box">
            <div class="row row-box">
                <div class="col-md-12" style="text-align: center;">
                    <div class="cardbox">
                    <h3 class="project-topic" style="margin-top: 5px">Lost & Found</h3>
                    <h5>รายชื่อสมาชิก</h5>
                    <p style="line-height: 2em;">
                        นาย จีระวัฒน์ หนักแน่น 5710450031<br>
                        นาย ธีระพล ไวยนิยี 5810613413<br>
                        นางสาว ศิริรัตน์ บุณยัษเฐียร 5910490035<br>
                        นาย ภูริณัฐ ธรรมราช 5910613347</p>
                    </div>
                </div>
            </div>
    </div>
    <div class="section-box">
        <div class="row">
            <div class="col-md-5">
                <div class="row row-box">
                    <div class="col-md-12">
                        <div class="cardbox head-topic">
                            <h4 class="project-topic">Document</h4>
                                <div class="row">
                                    <div class="col-md-1"></div>
                                    <div class="col-md-5"><p>
                                        <a href="https://drive.google.com/file/d/1VLooRiRulXW0MOmTysG1FS6iJ3AfDUw6/view?usp=sharing"><font style="color:red">ไฟล์ข้อเสนอ</font></a><br>
                                        <a href="https://drive.google.com/file/d/1CFpvjPLAAI06TLbod6XAZYnY0T1gnz15/view?usp=sharing"><font style="color:red">Feature</font></a></p>
                                    </div>
                                    <div class="col-md-1"></div>
                                    <div class="col-md-5"><p>
                                        <a href="https://drive.google.com/file/d/1ME-yGoZ0cqnUxqGe1vyvYMXLv-JT1EIx/view?usp=sharing"><font style="color:red">Requirements</font></a><br>
                                        <a href="https://drive.google.com/file/d/1FDn9RGvmxJxXc8k5sMsCssJV8XSrMkKt/view?usp=sharing"><font style="color:red">ER-Diagram</font></a></p>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-1"></div>
            <div class="col-md-6">
                <div class="row row-box">
                    <div class="col-md-12">
                        <div class="cardbox head-topic">
                            <h4 class="project-topic">Link</h4>
                            <div class="row">
                                <div class="col-md-12 text-center">
                                    <button class="button-link" onclick="window.location.href='https://www.pivotaltracker.com/n/projects/2223207'">Privotal Tracker</button>
                                    <button class="button-link" onclick="window.location.href='https://bitbucket.org/5810613413/testproject/src/poo-master'">Bitbucket Repository</button>
                                    <button class="button-link" onclick="window.location.href='https://youtu.be/j3vNVj_tsYg'">Youtube</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/found.html.erb
<div class="container">    
    <div class="section-box">
            <div class="row row-box">
                <div class="col-md-12" style="text-align: center;">
                    <div class="cardbox">
                    <h3 class="project-topic" style="margin-top: 5px">Found Items</h3>
                  
                </div>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/login.html.erb
<div class="container">    
    <div class="section-box">
            <div class="row row-box">
                <div class="col-md-12" style="text-align: center;">
                    <div class="cardbox">
                    <h3 class="project-topic" style="margin-top: 5px">Sign in</h3>
                    <div style="margin-left:20%">
                            <%= render 'sessions/form' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/lost.html.erb
<div class="container">    
    <div class="section-box">
            <div class="row row-box">
                <div class="col-md-12" style="text-align: center;">
                    <div class="cardbox">
                    <h3 class="project-topic" style="margin-top: 5px">Lost Items</h3>
                    
                    
                    </div>
                </div>
            </div>
    </div>
</div>

app/views/static_pages/signup.html.erb
<div class="container">    
    <div class="section-box">
            <div class="row row-box">
                <div class="col-md-12" style="text-align: center;">
                    <div class="cardbox">
                        <h3 class="project-topic" style="margin-top: 5px">Sign up</h3>
                        <div>
                            <%= render 'users/form' %>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>
  
  <span class="picture">
    <%= f.label :Image %><br>
    <% if f.object.picture? %>
      <%= image_tag f.object.picture.thumb.url %><br><br>
    <% end %>
    <%= f.file_field :picture %><br>
  </span>

  <%= f.submit yield(:button_text), class: "button" %>
  
<% end %>